export * from './aiController.service';
import { AiControllerService } from './aiController.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './commentController.service';
import { CommentControllerService } from './commentController.service';
export * from './communityController.service';
import { CommunityControllerService } from './communityController.service';
export * from './focusSessionController.service';
import { FocusSessionControllerService } from './focusSessionController.service';
export * from './postController.service';
import { PostControllerService } from './postController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AiControllerService, AuthControllerService, CommentControllerService, CommunityControllerService, FocusSessionControllerService, PostControllerService, UserControllerService];
