/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BadgeResDto { 
    id?: number;
    userId?: number;
    type?: BadgeResDto.TypeEnum;
     earnedAt?: string;
}
export namespace BadgeResDto {
    export const TypeEnum = {
        Beginner: 'BEGINNER',
        Learner: 'LEARNER',
        Explorer: 'EXPLORER',
        Contributor: 'CONTRIBUTOR',
        Helper: 'HELPER',
        Consistent: 'CONSISTENT',
        Collaborator: 'COLLABORATOR',
        Achiever: 'ACHIEVER',
        Mentor: 'MENTOR',
        Legend: 'LEGEND'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


