/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CommunityResDto { 
    id?: number;
    title?: string;
    description?: string;
    nbrMembers?: number;
    moderatorId?: number;
    category?: string;
}

