/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostResDto { 
    id?: number;
    title?: string;
    content?: string;
    imgs?: Array<string>;
    userUsername?: string;
    userFirstName?: string;
    userLastName?: string;
    communityTitle?: string;
}

