/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BadgeReqDto { 
    userId?: number;
    type?: BadgeReqDto.TypeEnum;
}
export namespace BadgeReqDto {
    export const TypeEnum = {
        BEGINNER: 'BEGINNER',
        LEARNER: 'LEARNER',
        EXPLORER: 'EXPLORER',
        CONTRIBUTOR: 'CONTRIBUTOR',
        HELPER: 'HELPER',
        CONSISTENT: 'CONSISTENT',
        COLLABORATOR: 'COLLABORATOR',
        ACHIEVER: 'ACHIEVER',
        MENTOR: 'MENTOR',
        LEGEND: 'LEGEND'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}

